### ISSUE TITLE
 [Cross-Check Portfolio] - moiseenokv

### ISSUE THREAD

**Issue by moiseenokv** [rolling-scopes-school/docs#57]
1) https://moiseenokv.github.io/portfolio/
2) https://github.com/moiseenokv/portfolio/
3) max score (64/100
- Minuses:
   - 1. Failure to adapt page for both desktop and mobile sizes may result in losing up to 40 points. **-30**
  - 2. No links to to my private social profiles **- 3**
  - 3. No animation in education block **-3**

4) 0

**Comment by amoebiusss** [comment]
Hello! In my opinion, the evaluation is as follows:

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **±** All links provided should navigate to real profiles on Social Networks. — **Only one "real" link provided**
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown. 
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **-** Interactive image in description (or whole description). When clicked, you should be navigated to project page. — **You can navigate to project page only by clicking the 'View Project' link. Image and description are not clickable**

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **±** All links or icons should navigate to real profiles on Social Networks. — **The same as for desktop, only one "real" link provided**
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **-** No arrows, project image should have all available width. — **Arrows are visible; image width exceeds screen width at several screen resolutions**
- **+** Swiper should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **-** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'. — **No button is presented, the overlay is being shown constantly**
- **-** Interactive image in description (except button and its label). When clicked, you should be navigated to project page. — **Image and description are not clickable. 'View Project' link is also not clickable (clicking on a link area causes slide switching). Project page can only be opened via the browser context menu or by direct link.**


###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 10 (project images are not clickable) - 3 (arrows do not hide on small screens) - 3 (no button for turning description showing on/off) - 5 (project link behavior issue) - 20 (some page elements are not adapted for small screens) = **59 points**

As you can see on the screenshot below, there are some issues with page adaptivity:
![moiseenokv github io_portfolio_(iPhone X)](https://user-images.githubusercontent.com/26903136/71416488-adf69600-2671-11ea-86ad-8a349ca98145.png)

#### Some remarks

1. It is always a good idea to use **width** and **height** attributes of an```<img>``` to set default image dimensions. It helps us prevent the page reflowing when loading images, because the size is already "reserved" for the image.

2.  In case you use BEM notation, try to avoid such selectors: ```projects__slider__nav__prev```. Such repetitive blocks/elements show that something is wrong with the approach. Here's the link to a quick tutorial just to help you recall some basic principles: https://en.bem.info/methodology/quick-start/

3. Slider buttons do not change page url, just switch slides. So I think, it’s better to use ```<button>``` elements to implement it. Please take a look at this simple algorithm how to choose between link and button: https://css-tricks.com/use-button-element/
```
<a href="#" class="projects__slider__nav__prev"> << </a> 
<a href="#" class="projects__slider__nav__next"> >> </a>
```

4. Please check validation results: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmoiseenokv.github.io%2Fportfolio%2F
It says there are some unescaped characters and also provides a way to fix this error — just to use special characters like ```&lt;``` for ```<``` sign and ```&gt;``` for ```>``` sign.

5. In your code, ```href``` attributes are set for ```<a>``` elements  with ```cta``` class . And then you change it from js in a click event listener (```window.location.href='projects.html';```) — this logic is not quite clear.

**Comment by moiseenokv** [comment]
Hello! Thanks for your time and comments. I agree with this evaluation mark - 59 points of common score. 
About remarks:
**In your code, href attributes are set for <a> elements with cta class . And then you change it from js in a click event listener (window.location.href='projects.html';) — this logic is not quite clear.**
while clickinhg on tag **a** with class cta -the main feature is to set in localstorage some key with value where value is url to the project. Then I use window.location.href attr to  projects.html page. And when this page starts loading - it takes url data from localstorage and put i n the iframe src attribute. For me it was the best and fast choice.
