### ISSUE TITLE
[Cross-Check Portfolio] - nextdesusu

### ISSUE THREAD

**Issue by nextdesusu** [rolling-scopes-school/docs#59]
1. https://stupefied-edison-c78870.netlify.com/
2. https://github.com/nextdesusu/portfolio
3. Оцениваю работу примерно в 90 баллов, каких то значимых недочетов не нашел, но мне кажется они есть, плюс не уверен в мобильной версии.
4. Текущий балл 66.

**Comment by amoebiusss** [comment]
Hello!

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite.
- **±** Description should have the list of main projects features. At least 2 of them. — **Actually it's not a list, just a paragraph of text**
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **±** No arrows, project image should have all available width. — **Project image doesn't have the entire available width**
- **-** Swiper should be infinite. — **Swiper does not work**
- **±** Description should have the list of main projects features. At least 2 of them. — **The same as for desktop**
- **+** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'.
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 10 (swiper doesn't work on mobile devices) - 3 (projects are not full-width on mobile devices) - 20 (issues with page adaptation) = **67 points**

The page does not correctly adapt to small screens, all page elements are too small — for example button is hardly noticeable and clickable, social links cannot be clicked without page zooming.

#### Some remarks.

1. In your code, ```<script>``` tag is outside ```<body>```,  that causes validation error. It is better to link external scripts before closing ```</body>``` tag, or in some cases it can be placed inside ```<head>```. ```<html>``` tag can **only** contain ```<head>``` element followed by ```<body>``` element, nothing more. Please note the **'Permitted content'** line: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html

2. Let's take a look at ```<img>``` tag in your code:
```
<img 
    pathToSrc="projects/repair-design-project/index.html"
    maxWidth="1440px"
    minWidth="375px"
     id="projects__slide2" class="projects__slide__image" 
    src="assets/images/slide__image__repair-design-project.png"
    >
```
```<img>``` tag **cannot have** pathToSrc, maxWidth or minWidth attributes, using it will cause errors. All possible attributes are listed here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img. Additionally, you can use **global** attributes, like ```class```, ```id```, ```hidden```, ```tabindex``` etc., or custom **data-attributes** (https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes), and there is no other options.

3. By the way, using ```alt``` attribute is **mandatory** for all content images of a document (that are placed with use of ```<img>```).

4. On the desktop, a single project opens in a modal **by double-clicking**. Actually, double-click is OK for desktop apps, but it definitely goes against the single-click interaction style on the web and should be avoided.

5. It is considered good practice to specify the language of a document language. Just use the ```lang``` attribute of the ```<html>``` tag, like this: ```<html lang="en">```.

6. Try to avoid such huge selectors like ```projetcs__slide__description__content__showing```. Something is wrong with the approach to class naming if you have such selectors in your code (not to mention multiple misprints).

7. It is better not to change styles directly from js, you can use a CSS class for styling and toggle it on click.
```
    // like here:
    function hideElems() {
        background.style.display = "none";
        buttonToggle.style.display = "none";
        buttonsContainer.style.display = "none";
        buttonExit.style.display = "none";
    }
```

8. ```let BUTTON_CONFIG``` — here you define a constant (judging by capitalization), but actually we can easily change its value, because it's a ```let``` variable.

9. As for animation — maybe it's a matter of taste, but now it feels like it is too slow and slightly braking. To make animation more user-friendly, please check out some popular animation guidelines, e.g. https://material.io/design/motion/speed.html#duration

10. And finally, try to get rid of lots of unnecessary commented code and empty CSS selectors in your code.
