### ISSUE TITLE
[Cross-Check Portfolio] – Juliya-Potapchuk

### ISSUE THREAD

**Issue by Juliya-Potapchuk** [rolling-scopes-school/docs#61]
1) https://juliya-potapchuk.github.io/portfolio/
2) https://github.com/Juliya-Potapchuk/portfolio
3) Минусы:
-Слайдер не бесконечный – 5 баллов
-Недоделанный адаптив страницы под моб. устройства – 7 баллов
-Нет перехода на страницу  ‘repair-design-project’ – 5 баллов
-Неплавная анимация – 5 баллов
-Аватар должен лежать в папке  ‘assets’– 5 баллов
Все требования по слайдеру были выполнены, за исключением того, что он должен быть цикличен.  Главная страница адаптивна, но не до конца. После 407px появляется горизонтальная прокрутка. Нет перехода на страницу проекта ‘repair-design-project’.  Ввиду того, что данное задание не было мною выполнено, соответственно, добавить переход на несуществующую страницу я не могу. Однако, несмотря на это, на главной странице в десктопной версии присутствует изображение проекта и место для его описания, а в мобильной предусмотрена кнопка с выпадающим описанием проекта. Что касается неплавной анимации и расположения изображения в папке ‘assets’, то в изначальных требованиях данных  пунктов не было, появились они на момент проверки уже готовых заданий.
Итого:  100 -5(слайдер) -7(адаптив) -5(‘repair-design-project’) =83 
4) Балл за cross-check:  53.

**Comment by amoebiusss** [comment]
Hi! Nice work, here's my evaluation:

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **-** Carousel should be infinite.  — **Carousel is not infinite**
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** No arrows, project image should have all available width. 
- **-** Swiper should be infinite. — **Swiper is not infinite**
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'.
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 5 (swiper is not infinite) - 10 (issues with page adaptation) = **85 points**

Some minor issues with page adaptation for small screens (< 400px width), text does not fully fit the screen:
![juliya-potapchuk github io_portfolio_index html(iPhone 6_7_8)](https://user-images.githubusercontent.com/26903136/71511268-c5689580-28a2-11ea-9e75-786ccb32364a.png)

#### Some remarks.

**1.** 
![Screen Shot 2019-12-27 at 11 00 42 AM](https://user-images.githubusercontent.com/26903136/71508237-28086400-2898-11ea-90ac-2a0cece38071.png)

This is a screenshot of your html code on my 24-inch display, yep :) The code becomes really unreadable, if you write it in one line.

In addition, why is "Show description" a ```<div>```? Why not use some element specifically designed to be a button? Even more, it can be only one button instead of two ```<div>```'s, the text inside it can be changed with js, and the arrow direction can be easily changed by using ```transform: rotate();``` css property.
___

**2.**
```html
<li>Media <span>q</span>uery</li>
```
If I understood well, ```<span>```'s are used here for uppercasing first letters of each word. You can just apply ```text-transform: capitalize;``` css property to the whole text for this purpose.
___

**3.** 
```html
<li><span>School</span> <br> <span class="years">2002 - 2011</span></li>
```
In this case, I think it's better to avoid using ```<br>```'s. ```<br>``` elements are good for adding line breaks in poems or, for example, addresses, e.g.:
```html
<p>
    USA,<br>
    New York,<br>
    11 Wall St.<br>
</p>
```
___

**4.** 
![Screen Shot 2019-12-27 at 11 37 34 AM](https://user-images.githubusercontent.com/26903136/71509702-4f156480-289d-11ea-9b86-e5e8f19aa9c0.png)

Here's a special link format for emails: ```<a href="mailto:some@email.com">```. Such link will open in the mail app installed on device. And you even can specify the email subject or body text, using this syntax. Please check: https://css-tricks.com/snippets/html/mailto-links/

And there's a similar feature for phone numbers: ```<a href="tel:+375291111111">``` - that's it, you just click on the link and the phone call will be initiated: https://css-tricks.com/the-current-state-of-telephone-links/
<hr>

**5.** Logical parts of layout are divided into ```<section>```'s, that's good. Another good practice is to wrap the primary page content into a ```<main>``` tag.
___

**6.** Do you really need that bunch of vendor prefixes for your target browsers? For example, check the flexbox support, paying attention to the "supported with prefix" lines and corresponding browser versions: https://caniuse.com/#feat=flexbox
```css
.swiper-slide {
    background: #fff;
    /* Center slide text vertically */
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
}
```
___

**7.** Let's take a look at this piece of code:
```html
<div class="head-list">
    <h2>Education</h2>
    <i class="fa fa-align-justify" aria-hidden="true" ></i>
</div>
```
The **Education** panel expansion occurs when you click on the panel. So, when using VoiceOver / another screenreader / some other assistive technology, there is no way to expand this block, because the element is just not visible for a reader (and the same for the **Projects** panel). You can easily check it yourself. Just install this (or any other suitable) extension and try to navigate through a page by clicking **Tab** button on your keyboard: https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en

Possible solution is to make this "burger-menu" sign a button:
```html
<button>With descriptive text inside it - e.g. "Expand list / Show details / etc."</button>
```
Then to make this text invisible with CSS (but still available for screenreaders), use an icon as the button background and implement click handling logic.
___

**&ast;** If something is supposed to be clickable, but really it's not, it would be better to make this element disabled, or write warning in description, or show some modal with a message (talking about a nonexistent "repair-design-project":). Actually, this is not directly connected with html or css, but I think this is a kind of error handling and should be implemented in friendly user interfaces.

**Comment by Juliya-Potapchuk** [comment]
Здравствуйте! Спасибо большое за оценку и за полезные замечания:)
