### ISSUE TITLE
[Cross-Check Portfolio] – 'gitmaxx'

### ISSUE THREAD

**Issue by gitmaxx** [rolling-scopes-school/docs#63]
1. https://mx-portfolio.netlify.com/
2. https://github.com/gitmaxx/portfolio
3. Оценка: 98 баллов.  Штраф 2 балла за отсутствие плавной анимации
4. 75 баллов

**Comment by amoebiusss** [comment]
Hello! Here's my evaluation:

### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **-** Smooth animation.  — **No smooth animation**
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite. 
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **-** Smooth animation.  — **No smooth animation**
- **±** No arrows, project image should have all available width.   — **Project image has fixed size**
- **+** Swiper should be infinite.
- **+** Description should have the list of main projects features. At least 2 of them.
- **+** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'.
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **+** Only 1 button exists on mobile version.
- **+** When you are on mobile, and click 'back', you should be navigated to original portfolio page.

## Evaluation
100 points (max) - 3 (no smooth animation) - 3 (no full-width images on mobile) = **94 points**

### Some remarks

1. 
```html
 <div class="slide_image">
    <img class="image" src="assets/images/yalow.png" alt="project">
    <img class="image image--mobile image--mobile-active" src="assets/images/yalowmobile.png" alt="project">
</div>
```
In order not to duplicate images, you can use a single ```<img>``` tag and set multiple resolutions using the ```srcset``` attribute, no JS needed. More about this: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

If you want to change not only the image size depending on the screen resolution, but use different images for different screens, take a look at ```<picture>``` tag. Inside it, you can define multiple ```<source>``` tags for each resolution (and by the way, ```srcset``` can also be used for each of ```<source>``` tags), and add an ```<img>``` tag as a fallback. Here's a tutorial: https://www.html5rocks.com/en/tutorials/responsive/picture-element/
___

2. 
```html
<div class="control_panel control_panel-left">
    <div class="direction_pointer">&lt;</div>
</div>
```
When looking at this code, it’s not entirely clear what kind of element it is — some kind of arrow, or maybe a control that changes the direction of filtering, or just a random ```<div>```. Why not use ```<button>``` tags instead of ```<div>```'s to implement buttons?
___

3. You use some shorthand css properties in your code. It can be shortened even more, e.g.:
```css
    margin: 10px 0 10px 0;
    /* can be shortened to: */
    margin: 10px 0;

    padding: 0px 12px 12px 12px;
    /* can be shortened to: */
    padding: 0 12px 12px;
```

But it's better to be careful with the shorthands like this one: ```details {  background: #fff;  }```, because actually you are applying the following styles:
```css
details {
  background-image: initial;
  background-position-x: initial;
  background-position-y: initial;
  background-size: initial;
  background-repeat-x: initial;
  background-repeat-y: initial;
  background-attachment: initial;
  background-origin: initial;
  background-clip: initial;
  background-color: #ffffff;
}
```
So in this case it would be better just to set background-color: ``` details { background-color: #ffffff; 
 }``` 
___

4. It would be more obvious if the cursor had ```pointer``` value while being above the links:
![cursor](https://user-images.githubusercontent.com/26903136/71583857-3b7a3000-2b21-11ea-8eed-7072c27625c2.png)

Cursor appearance can be modified by using ```cursor``` css property: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
___

5. I think, such logic can make code maintenance a bit complicated - for example, in case we want to add a couple of slides:
```javascript
...
switch (document.querySelector('.slide-active').id) {
    case '1':
        linkToProject = 'projects/theyalow/index.html';
        projectName = 'theyalow';
        break;
    case '2':
        linkToProject = 'projects/repair-design-project/index.html';
        projectName = 'repair';
        break;  
}
...
```

**&ast;** And maybe it will be interesting for you - an opinion on why ```<details>``` tag is not an accordion: https://daverupert.com/2019/12/why-details-is-not-an-accordion/

**Comment by gitmaxx** [comment]
Thanks a lot! :)
