### ISSUE TITLE
 [Cross-Check Portfolio] - 'Qairkhan'

### ISSUE THREAD

**Issue by Qairkhan** [rolling-scopes-school/docs#64]
1.  https://qairkhan.github.io/portfolio/
2. https://github.com/Qairkhan/portfolio
3. Оценка: ~ 85 . отсутствует описание  
4. 0 - видимо, были проблемы с сабмитами

**Comment by Ambrance** [comment]
Max 100
-5 баллов за просрочку дедлайна
-15 баллов суммарно за все видимые недостатки по верстке на десктопе и мобильном (скролл, выпадание контента, отсутствие центровки страниц проектов)
-5 баллов за не меняющуюся надпись на кнопке "show/hide description"
-5 отсутствие описания проектов
-20 баллов за copy/paste
Итог: 50

**Comment by Qairkhan** [comment]
Ok

**Comment by Qairkhan** [comment]
Thx

вт, 31 дек. 2019 г., 13:28 Inesa Bobryk <notifications@github.com>:

**Comment by amoebiusss** [comment]
### **Desktop** 
- **+** Avatar should be image in assets folder.
- **+** All links provided should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** Interactive arrows left and right, which switch the next and the previous project.
- **+** Carousel should be infinite.
- **±** Description should have the list of main projects features. At least 2 of them. — **Actually it's not a list, just paragraphs of text + it's a lorem ipsum**
- **+** Interactive image in description (or whole description). When clicked, you should be navigated to project page.

###  **Mobile**
- **+** Avatar should be image in assets folder.
- **+** All links or icons should navigate to real profiles on Social Networks.
- **+** Interactive expansion panel. Should be inactive on render. When press on any place over the line 'Education', the list should be shown.
- **+** Items in list wrapped with HTML list (ul or ol).
- **+** Smooth animation.
- **+** No arrows, project image should have all available width.
- **+** Swiper should be infinite.
- **±** Description should have the list of main projects features. At least 2 of them. — **The same as for desktop**
- **-** When the description button is clicked, it should show the description overlay above the image. And name near the button should switch text to 'hide description'. — **No overlay, button text does not change**
- **+** Interactive image in description (except button and its label). When clicked, you should be navigated to project page.

###  **Project page**
- **+** 2 buttons exist on desktop version.
- **+** When you are on desktop, and click 'mobile', the view should be switched to centered mobile one and margins on left and right. Name of button should be changed properly. Second click will revert project to desktop view again.
- **+** When you are on desktop, and click 'back', you should be navigated to original portfolio page.
- **±** Only 1 button exists on mobile version. — **Actually the button exists, but not visible because of adaptation issues - so you need to zoom/scroll the page to find it**
- **±** When you are on mobile, and click 'back', you should be navigated to original portfolio page. — **The same as for the previous item**

## Evaluation
100 points (max) - 25 (adaptive layout issues) - 5 ('back' button is not accessible due to adaptation issues) - 5 (no feature list in project description) - 5 ('show description' button text does not change) - 5 (description is not in an overlay on small screens) - **?** (copypaste) = **55 points** - **'?' points** = **NaN points**

The page does not correctly adapt to small screens. And yes, it looks like I'm reviewing someone else's portfolio (https://youtu.be/xYxO2UzXmec?t=1385)

#### Some remarks.

1. ```alt``` attribute is required for ```<img>``` tags.

2. The ```frameborder``` attribute on the ```<iframe>``` element is obsolete. You should not use it.

3.  It's not an error, but ```navigation``` role is unnecessary for the ```<nav>``` element.

4.  Also not an error, but it's better to provide headings for all ```<sections>```.

5. Avoid using such class naming:```<section class="ed">```

5. Copying and pasting will not teach you anything other than copying and pasting.
